server:
  port: 10001
spring:
  application:
    name: tues-bitcoin

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(DI9iXNL4PUxC4zOhd4I00cbzB0TLicu9eb3RHNio4dDm6uinKLOhzuae0O73E6ImWCrcvSoc466PwyEkz5GP9kgUPcx+EGtSMFGiE4eLHfcQVz4FNP5cIA3AiFsnmClLLCPwrPwOcmi5ABG7xVfY4UyIrVAwBjZz9FvbZ4+2x2T1g0JH01x/EPC2J50xmqG6)
    username: ENC(le89BOO33fezSsQl/4kzpg==)
    password: ENC(K6vVvNk53bp61G9ncufyZm9qes75AwEO)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

bitcoin:
  currencyName: BTC
  nodeurl: ENC(Tjb6kL/GtwmUingUiNQEoxRlEQaBSO7+mJ7iQvMgOAdYX3yU+185LPap1GfQLHNo) #节点地址,包含了RPC账号和密码

jasypt:
  encryptor:
    password: yoursecret #配置EncryptPropertiesUtils工具类里填写的秘钥，最好在命令行注入参数
